pipeline {
agent any

```
tools {
    jdk 'JDK17'
    maven 'Maven3'
}

stages {

    stage('Checkout Code') {
        steps {
            git branch: 'main',
                url: 'https://github.com/AryanRajJha/wipro-capstone-project.git'
        }
    }

    stage('Clean Project') {
        steps {
            bat 'mvn clean'
        }
    }

    stage('Compile Project') {
        steps {
            bat 'mvn compile'
        }
    }

    stage('Run TestNG Tests') {
        steps {
            bat 'mvn test'
        }
    }

    stage('Generate Reports') {
        steps {
            echo 'Collecting Test Reports'
        }
    }
}

post {

    always {
        archiveArtifacts artifacts: 'test-output/**/*', allowEmptyArchive: true

        publishHTML([
            allowMissing: true,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'test-output',
            reportFiles: 'emailable-report.html',
            reportName: 'TestNG Report'
        ])
    }

    success {
        echo 'Tests Executed Successfully'
    }

    failure {
        echo 'Build Failed'
    }
}
```

}
